### ISSUE TITLE
Missing nginx-proxy dependencies

### ISSUE THREAD

**Issue by heralight** [dm/rancher-catalog-elk#1]
Hello,

Thank you for template!
When use on rancher, I need to delete lines related to nginx-proxy in dev version.
What did I miss, please ?

Alexandre

**Comment by emcniece** [comment]
Also seeing this on the single-host v5.4.1-rancher.1. Error:

```
 Error (Bad response statusCode [422]. Status [422 status code 422]. Body: [code=InvalidReference, fieldName=network_from of service cerebro is referencing a service nginx-proxy that either does not exist or is not properly labeled as a sidekick, baseType=error] from [http://localhost:8080/v2-beta/projects/1a50/services])
```

The `net: ` syntax is from Docker-Compose V1, used to create scoped networks for a set of containers. Lines 7 and 48 of [docker-compose.yml](https://github.com/dm/rancher-catalog-elk/commit/5a1dffed9b80e67f0d718121fda3543be712bc45#diff-93f7cdcb52a0e470aedf25181c52f35b) indicate that these containers (cerebro and kibana) should share a network with a container named "nginx-proxy", yet there is no such container in this stack.

I'd guess that the "nginx-proxy" container was either deprecated or exists outside of the scope of this template. Its purpose was likely to forward browser traffic to the dashboard.

These two lines can and should be removed. They do not exist in the scalable template version. It will be up to you to forward traffic to the Kibana container.

**Comment by dm** [comment]
Hi @heralight, @emcniece is correct, it's been deprecated and will be removed.
I'll have to update these, including latest versions, and bring it in compliance with the official format in order to get this merged.
Will need this for work too, so likely to be fixed in the next month (or couple of months). Cheers!
